version: '3'

services:
  at-samba:
    tty: true
    network_mode: bridge
    volumes:
      - /mnt/d/Projects/:/Shared
    ports:
      - "445:445"
    build:
      context: samba/
      dockerfile: Dockerfile